FROM apache/airflow:latest-python3.9
# Denna är viktig för att se till så att den hittar rätt path när man ska
# hämta en .py modul från typ en annan map och som man inte listas
# i import sys -> sys.path 
ENV PYTHONPATH=/opt/airflow
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
