FROM python:3.9

# Set the working directory
WORKDIR /E01

# Copy the script files and directories
# COPY cron_schedule /app/cron_schedule
COPY folderlogs .
COPY src .


COPY installed_packages.sh .
COPY running_scripts.sh .
COPY python_script.py .

# Make the script files executable
RUN chmod +x installed_packages.sh running_scripts.sh

# Define the command to run when the container starts
CMD ["python", "./running_scripts.sh"]



#-----------------------------------
# # # FROM python:3.9

# # # WORKDIR /E01

# # # COPY src .

# # # COPY installed_packages.sh .

# # # COPY folderlogs .

# # # RUN pip install matplotlib plotly_express pandas numpy dash scikit-learn

# # # RUN apt update && apt install cron nano -y


# # # CMD ["python", "./ex1_0_setup.py"]

# # # # This is the python script that the cron schedule is gonna run but now the issue is i can't have multiple CMDs
# # # # so i need to figure out how to run this script after the setup script has run.
# # # CMD ["python", "folderlogs/countdown.py"]


#------------------------------------------------------------------------------

# Outcommented last to go back and see if it works in another way. However i think to fix this issue, we need
# to copy cron_schedule h

# FROM python:3.9

# WORKDIR /E01

# COPY src .
# COPY installed_packages.sh .
# COPY folderlogs .

# # Adding cron schedule file
# COPY cron_schedule .

# # Install cron and other dependencies
# RUN pip install matplotlib plotly_express pandas numpy dash scikit-learn
# RUN apt update && apt install cron nano -y

# RUN crontab cron_schedule

# CMD ["python", "./ex1_0_setup.py", "cron", "-f"]



