FROM python:3.9

WORKDIR /E01

ADD src .

RUN pip install matplotlib plotly_express pandas numpy dash scikit-learn

CMD ["python", "./ex1_0_setup.py"]


# FROM python:3.9

# WORKDIR /Users/joeloscarsson/Documents/www/DataEngineering/exercises/E01

# RUN pip install matplotlib plotly_express pandas numpy dash scikit-learn

# COPY src/ex1_0_setup.py .

# CMD ["python", "ex1_0_setup.py"]



